/**
 * Hacker Planet LLC - drop-ship catalog (retail prices)
 *
 * Customer pays HPL via Stripe -> you order from supplierUrl -> ships to customer.
 * supplierUrl is for your fulfillment ops (also in docs/DROPSHIP_CATALOG.md).
 */
window.HPL_CATALOG = {
  dropshipNote: "Partner fulfillment | 5-14 business days | authorized lab use only",
  affiliate: {
    aliexpress: "",
    etsy: "",
    tindie: "",
  },
  sections: [
    {
      id: "gotchi-pods",
      label: "Cyber wardrive pods",
      title: "Pwnagotchi | Netgotchi | night-hunter field pods",
      banner: "images/banner-gotchi-pods.png",
      intro:
        "Cyber wardrive pods - compact WiFi lab hardware ships from verified makers. Mid-range Kali-ready configs available on request.",
      products: [
        {
          id: "ds-pwnagotchi",
          name: "Pwnagotchi - assembled wardrive pod",
          image: "images/products/ds-pwnagotchi.png",
          retailPrice: 169,
          priceDisplay: "$169",
          fulfillment: "dropship",
          stripeKey: "dsPwnagotchi",
          fulfillmentChannel: "ebay",
          ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=pwnagotchi+assembled+oled",
          supplierUrl: "https://www.etsy.com/market/pwnagotchi",
          supplier: "Etsy / community makers",
          source: "dropship",
          description:
            "Community-assembled Pi Zero W or ESP32 wardrive pod with OLED telemetry panel - passive WiFi observation for authorized labs. Board, display theme, and enclosure vary by maker; tell us your preferences at checkout and we route to a matching Etsy build.",
          includes: ["Flashed SD image", "OLED status panel", "Pi Zero W or ESP base", "USB power cable"],
          badge: "Wardrive",
        },
        {
          id: "ds-netgotchi",
          name: "Netgotchi - defensive network guardian",
          image: "images/products/ds-netgotchi.jpg",
          retailPrice: 99,
          priceDisplay: "$99",
          fulfillment: "dropship",
          stripeKey: "dsNetgotchi",
          fulfillmentChannel: "etsy",
          ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=netgotchi+defensive",
          supplierUrl: "https://olleadventures.etsy.com/listing/1752764124",
          supplier: "OlleAdventures",
          source: "dropship",
          description:
            "NETGOTCHI v2 from OlleAdventures - Pwnagotchi's defensive sibling: honeypot, intrusion alerts, and periodic 2.4 GHz WiFi scans. Expandable case with OLED and speaker; open-source firmware on GitHub. Case color is the only customization - message your preference (default black or blue) at checkout.",
          includes: ["Assembled board + case", "OLED + speaker", "Micro USB cable", "Open-source firmware"],
          badge: "Defensive",
        },
        {
          id: "ds-netgotchi-pro",
          name: "Netgotchi Pro - keypad + buzzer",
          image: "images/products/ds-netgotchi-pro.jpg",
          retailPrice: 129,
          priceDisplay: "$129",
          fulfillment: "dropship",
          stripeKey: "dsNetgotchiPro",
          supplierUrl: "https://olleadventures.etsy.com/listing/1771783598",
          supplier: "OlleAdventures",
          source: "dropship",
          description:
            "NETGOTCHI PRO - portable network guardian with keypad, buzzer, TEXTgotchi mode, and on-device settings. Scans and protects 2.4 GHz networks; expandable case. Customization is case color only - note your choice at checkout.",
          includes: ["Keypad + buzzer", "Expandable case", "OLED + speaker", "USB cable"],
        },
        {
          id: "ds-night-hunter",
          name: "Night Hunter pod - Kali-ready field build",
          image: "images/products/ds-night-hunter.jpg",
          retailPrice: 189,
          priceDisplay: "$189",
          fulfillment: "dropship",
          stripeKey: "dsNightHunter",
          supplierUrl: "https://www.tindie.com/products/honeyhoneytrading/esp32-marauder-pocket-unit-with-gps-v2/",
          supplier: "HoneyHoneyTrading",
          source: "dropship",
          description:
            "ESP32 Marauder Pocket Unit with GPS v2 - 2.8\" touchscreen, dual SMA WiFi/BT antennas, wardrive GPS, dual 18650 bays, SD PCAP storage, and 3D-printed enclosure (~9.2x4.6x7.1 cm). Enclosure color is the listing customization; we pass your choice to HoneyHoneyTrading.",
          includes: ["CYD 2.8\" touchscreen", "GPS + dual SMA", "8GB SD", "Printed enclosure"],
          badge: "Kali-ready",
        },
      ],
    },
    {
      id: "meshtastic",
      label: "Meshtastic",
      title: "Meshtastic mesh radio kits",
      intro:
        "Off-grid LoRa mesh nodes - turnkey Etsy builds and kit options ship to your authorized lab. Operator places supplier orders manually after HPL checkout.",
      products: [
        {
          id: "ds-meshtastic-tbeam",
          name: "LilyGO T-Beam v1.1 Meshtastic kit",
          image: "images/products/ds-meshtastic-tbeam.png",
          retailPrice: 89,
          priceDisplay: "$89",
          fulfillment: "dropship",
          stripeKey: "dsMeshtasticTBeam",
          supplierUrl: "https://www.lilygo.cc/products/t-beam-v1-1",
          supplier: "LilyGO / AliExpress",
          source: "dropship",
          description:
            "Classic Meshtastic backpack node - ESP32 + SX1276 LoRa + GPS, battery holder, and antenna. LilyGO ships multiple LoRa band options; tell us your region at checkout and we order the matching band.",
          includes: ["T-Beam v1.1 board", "GPS module", "LoRa antenna", "Battery holder"],
          badge: "LoRa mesh",
        },
        {
          id: "ds-meshtastic-heltec",
          name: "Heltec V3 fully built Meshtastic node",
          image: "images/products/ds-meshtastic-heltec.jpg",
          retailPrice: 129,
          priceDisplay: "$129",
          fulfillment: "dropship",
          stripeKey: "dsMeshtasticHeltec",
          buildType: "fully_built",
          supplierUrl: "https://www.etsy.com/listing/1733234765/the-knight-complete-device-heltec-v3",
          supplier: "LayerFabUK (Etsy)",
          source: "dropship",
          description:
            "Turnkey Heltec WiFi LoRa 32 V3 mesh radio - professionally assembled, flashed for Meshtastic, and housed in a field-ready printed case. Routed through LayerFabUK, an Etsy Star Seller with consistent five-star reviews. Specify US 915 MHz (or your region) at checkout; we place the matching variant with the maker.",
          includes: [
            "Heltec V3 with Meshtastic firmware",
            "Printed protective case",
            "Long-range LoRa antenna",
            "Battery + USB charge path",
          ],
          badge: "Fully built",
        },
        {
          id: "ds-meshtastic-rak",
          name: "RAK4631 Meshtastic starter kit",
          image: "images/products/ds-meshtastic-rak.webp",
          retailPrice: 119,
          priceDisplay: "$119",
          fulfillment: "dropship",
          stripeKey: "dsMeshtasticRAK",
          supplierUrl: "https://store.rakwireless.com/products/wisblock-meshtastic-starter-kit",
          supplier: "RAKwireless",
          source: "dropship",
          description:
            "WisBlock Meshtastic Starter Kit - RAK4631 (nRF52840 + SX1262) pre-flashed, 2 dBi rubber antenna, BLE antenna, USB cable. Pick base board size and optional OLED/GNSS modules on RAKwireless; customization is module mix only.",
          includes: ["RAK4631 core (Meshtastic FW)", "WisBlock base", "2 dBi LoRa antenna", "USB cable"],
          badge: "Starter",
        },
        {
          id: "ds-meshtastic-case",
          name: "Meshtastic 3D-printed field case",
          image: "images/products/ds-meshtastic-case.jpg",
          retailPrice: 34,
          priceDisplay: "$34",
          fulfillment: "dropship",
          stripeKey: "dsMeshtasticCase",
          supplierUrl: "https://www.etsy.com/search?q=meshtastic+case+3d+print",
          supplier: "Etsy makers",
          source: "dropship",
          description:
            "Weather-resistant printed enclosure for T-Beam or Heltec - routed through Etsy makers. Case color and board fit (T-Beam vs Heltec) are the only customization; note your board model at checkout.",
          includes: ["Printed top/bottom", "Mounting hardware", "Antenna passthrough"],
        },
      ],
    },
    {
      id: "hackberry",
      label: "Hackberry Pi",
      title: "Hackberry Pi cyberdecks (ZitaoTech)",
      intro:
        "BlackBerry-keyboard Linux handhelds - Kali-ready cyberdecks ship from ZitaoTech / community distributors.",
      products: [
        {
          id: "ds-hackberry-zero",
          name: "Hackberry Pi Zero - pocket Kali terminal",
          image: "images/products/ds-hackberry-zero.png",
          retailPrice: 279,
          priceDisplay: "$279",
          fulfillment: "dropship",
          stripeKey: "dsHackberryZero",
          supplierUrl: "https://www.elecrow.com/hackberrypi-zero-with-q10-keyboard.html",
          supplier: "ZitaoTech / Elecrow",
          source: "dropship",
          description:
            "Handheld Linux terminal - Raspberry Pi Zero 2 W, 720x720 TFT, BlackBerry keyboard (Q10/Q20/9900), three USB ports, swappable Nokia BL-5C cells. Keyboard layout is the main supplier customization.",
          includes: ["Assembled deck", "BB keyboard", "Batteries", "Type-C charge"],
          badge: "Cyberdeck",
        },
        {
          id: "ds-hackberry-pi5",
          name: "Hackberry Pi 5 - full cyberdeck",
          image: "images/products/ds-hackberry-pi5.png",
          retailPrice: 449,
          priceDisplay: "$449",
          fulfillment: "dropship",
          stripeKey: "dsHackberryPi5",
          supplierUrl: "https://www.tindie.com/products/zitaotech/hackberrypi5-with-9900-keyboard/",
          supplier: "ZitaoTech / Tindie",
          source: "dropship",
          description:
            "Pi 5 cyberdeck with 720x720 touch display, dual 18650 power, stereo Bluetooth speakers, VIAL keymaps, Stemma I2C - runs Kali or Raspberry Pi OS. Keyboard and plate options are configured with ZitaoTech.",
          includes: ["Pi 5 slot build", "720x720 touch", "Stereo BT speakers", "Stemma I2C"],
        },
        {
          id: "ds-hackberry-cm5",
          name: "Hackberry Pi CM5 - ultra portable",
          image: "images/products/ds-hackberry-cm5.png",
          retailPrice: 499,
          priceDisplay: "$499",
          fulfillment: "dropship",
          stripeKey: "dsHackberryCM5",
          supplierUrl: "https://github.com/ZitaoTech/HackberryPiCM5",
          supplier: "ZitaoTech",
          source: "dropship",
          description:
            "CM5 compute module in aluminium body - NVMe slot, USB 3, HDMI out, dual speakers. Ultra-portable pro deck; enclosure and keymap are the configurable options from ZitaoTech.",
          includes: ["CM5-compatible shell", "Dual speakers", "Metal plates", "3D mid-frame"],
          badge: "Pro",
        },
      ],
    },
    {
      id: "marauder-wifi",
      label: "Marauder & WiFi lab",
      title: "ESP32 Marauder | Deauther | custom builds",
      intro: "Authorized RF lab tools - GPS wardrive builds and battery mods ship from partner makers.",
      products: [
        {
          id: "ds-marauder-gps",
          name: "Marauder pocket + GPS v2",
          image: "images/products/ds-marauder-gps.jpg",
          retailPrice: 219,
          priceDisplay: "$219",
          fulfillment: "dropship",
          stripeKey: "dsMarauderGps",
          supplierUrl: "https://www.tindie.com/products/honeyhoneytrading/esp32-marauder-pocket-unit-with-gps-v2/",
          supplier: "HoneyHoneyTrading",
          source: "dropship",
          description:
            "HoneyHoneyTrading ESP32 Marauder Pocket with GPS v2 - wardrive logging, dual SMA antennas, 8GB SanDisk SD, 2.8\" CYD touchscreen, dual 18650 (batteries not shipped). Case color is the only customization on the listing.",
          includes: ["GPS module", "WiFi/BT antennas", "8GB SD", "USB-C charge"],
        },
        {
          id: "ds-marauder-battery",
          name: "CYD battery + GPS mod kit",
          image: "images/products/ds-marauder-battery.jpg",
          retailPrice: 59,
          priceDisplay: "$59",
          fulfillment: "dropship",
          stripeKey: "dsMarauderBatteryMod",
          supplierUrl: "https://biscuitshop.us/products/esp32-marauder-battery-mod-kit",
          supplier: "Biscuit Shop",
          source: "dropship",
          description:
            "Biscuit Shop V2 drop-in PCB for Cheap Yellow Display - no soldering, adds LiPo power, I2C fuel gauge, and GPS for Marauder wardrive builds.",
          includes: ["GPS antenna", "Charge circuit", "Plug-in PCB"],
        },
        {
          id: "ds-marauder-koko",
          name: "Official Marauder Kit (Koko PCB)",
          image: "images/products/ds-marauder-koko.jpg",
          retailPrice: 89,
          priceDisplay: "$89",
          fulfillment: "dropship",
          stripeKey: "dsMarauderKoko",
          supplierUrl: "https://www.tindie.com/products/justcallmekoko/esp32-marauder-kit/",
          supplier: "JustCallMeKoko",
          source: "dropship",
          description:
            "JustCallMeKoko official ESP32 Marauder kit - PCB and 3D-printed enclosure; you supply Huzzah32 and LiPo. Portable WiFi/BT analysis firmware.",
          includes: ["PCB", "3D printed case", "Screws", "QR docs"],
        },
      ],
    },
    {
      id: "sbc-hacker",
      label: "SBC & Pi kits",
      title: "Raspberry Pi | Orange Pi | edge router boards",
      intro: "Mid-range hacker SBC kits ship from AliExpress / official distributors - vetted sellers only.",
      products: [
        {
          id: "ds-rpi5-kit",
          name: "Raspberry Pi 5 starter kit (8GB class)",
          image: "images/products/ds-rpi5-kit.jpg",
          retailPrice: 159,
          priceDisplay: "$159",
          fulfillment: "dropship",
          stripeKey: "dsRaspberryPi5",
          fulfillmentChannel: "ebay",
          ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=raspberry+pi+5+8gb+starter+kit",
          amazonSearchUrl: "https://www.amazon.com/s?k=raspberry+pi+5+8gb+starter+kit",
          supplierUrl: "https://www.canakit.com/raspberry-pi-5.html",
          supplier: "CanaKit (authorized reseller)",
          source: "dropship",
          description:
            "Pi 5 board + active cooler + 27W PSU + case - homelab IDS or CyberThreatGotchi dev bench. RAM tier (4GB vs 8GB) and case color are the supplier variants; specify your preference at checkout.",
          includes: ["Pi 5 board", "Active cooler", "Power supply", "Case"],
        },
        {
          id: "ds-orange-pi5",
          name: "Orange Pi 5 Plus (8GB) kit",
          image: "images/products/ds-orange-pi5.jpg",
          retailPrice: 119,
          priceDisplay: "$119",
          fulfillment: "dropship",
          stripeKey: "dsOrangePi5",
          fulfillmentChannel: "aliexpress",
          ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=orange+pi+5+plus+8gb",
          aliexpressSearchUrl: "https://www.aliexpress.com/w/wholesale-orange-pi-5-plus.html",
          supplierUrl: "https://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5-plus.html",
          supplier: "AliExpress / Orange Pi store",
          source: "dropship",
          description:
            "RK3588 SBC for lightweight SIEM edges and portable lab stacks. RAM and storage bundle options vary on AliExpress - tell us your target config at checkout.",
          includes: ["8GB RAM variant", "Heatsink", "Power adapter"],
        },
        {
          id: "ds-bpi-r3",
          name: "Banana Pi BPI-R3 Mini router SBC",
          image: "images/products/direct-core-kit.jpg",
          retailPrice: 119,
          priceDisplay: "$119",
          fulfillment: "dropship",
          stripeKey: "dsBananaPiR3",
          catalogHidden: true,
          fulfillmentChannel: "ebay",
          ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=banana+pi+bpi-r3+mini+2gb",
          aliexpressSearchUrl: "https://www.aliexpress.com/w/wholesale-banana-pi-r3-mini.html",
          supplierUrl: "https://www.banana-pi.org/",
          supplier: "AliExpress",
          source: "dropship",
          description:
            "CTG component only - the BPI-R3 Mini is assembled inside the Philadelphia CyberThreatGotchi core kit (~$160 board cost at May 2026 supplier floor). Hidden from shop; ops spare-board key only.",
          includes: ["BPI-R3 Mini", "Antennas", "Optional case"],
        },
        {
          id: "ds-esp32-lab",
          name: "ESP32 CYD lab bundle (x2 boards)",
          image: "images/products/ds-esp32-lab.jpg",
          retailPrice: 49,
          priceDisplay: "$49",
          fulfillment: "dropship",
          stripeKey: "dsEsp32Cyd",
          fulfillmentChannel: "ebay",
          ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=esp32-2432S028R+cheap+yellow+display",
          aliexpressSearchUrl: "https://www.aliexpress.com/w/wholesale-esp32-2432S028R.html",
          supplierUrl: "https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display",
          supplier: "AliExpress / Makerfabs (vetted)",
          source: "dropship",
          description:
            "Two ESP32-2432S028R Cheap Yellow Display modules - integrated 2.8\" touch TFT for Marauder, Bruce, or LVGL lab dashboards. Operator orders the resistive-touch ILI9341 variant from a vetted marketplace listing (see community pinout guide).",
          includes: ["2x CYD 2.8\"", "USB cables", "Basic antennas"],
        },
        {
          id: "ds-wiring-lab",
          name: "Breadboard + jumper wiring lab kit",
          image: "images/products/direct-core-kit.jpg",
          retailPrice: 22,
          priceDisplay: "$22",
          fulfillment: "dropship",
          stripeKey: "dsWiringLab",
          supplierUrl: "https://www.sparkfun.com/jumper-wire-kit-140pcs.html",
          supplier: "SparkFun / Adafruit",
          source: "dropship",
          description:
            "Bench prototyping pack - half-size breadboard plus pre-cut 22 AWG jumper sets for CYD, Pi, and ESP32 bring-up. Ships from US maker distributors; ideal companion for homelab kit orders.",
          includes: ["Half-size breadboard", "140x pre-bent jumpers", "Color-coded solid core set"],
          badge: "Lab essentials",
        },
      ],
    },
    {
      id: "rf-network-lab",
      label: "RF & network lab",
      title: "SDR | passive tap | authorized WiFi lab tools",
      intro:
        "Curated partner fulfillment for authorized lab environments — spectrum monitoring, passive Ethernet visibility, and training-grade tools. Offensive-capable SKUs require written scope and owned targets only.",
      products: [
        {
          id: "ds-rtl-sdr-kit",
          name: "RTL-SDR Blog V3 starter kit",
          image: "images/products/direct-core-kit.jpg",
          retailPrice: 99,
          priceDisplay: "$99",
          fulfillment: "dropship",
          stripeKey: "dsRtlSdrKit",
          fulfillmentChannel: "amazon",
          supplierUrl: "https://www.sparkfun.com/rtl-sdr-blog-v3-usb-dongle-with-dipole-antenna-kit.html",
          amazonSearchUrl: "https://www.amazon.com/s?k=rtl-sdr+blog+v3+dipole+antenna+kit",
          ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=rtl-sdr+blog+v3+dipole",
          supplier: "SparkFun / RTL-SDR Blog",
          source: "dropship",
          description:
            "RTL-SDR Blog V3 USB dongle with dipole antenna kit — receive-only spectrum lab for ADS-B, pager, and ISM survey on authorized networks. Operator sources from SparkFun or Amazon RTL-SDR Blog storefront; we ship curated quick-start scope to your lab.",
          includes: ["RTL-SDR V3 dongle", "Dipole antenna kit", "SMA adapter", "Authorized-lab quick-start"],
          badge: "SDR starter",
        },
        {
          id: "ds-nesdr-smart",
          name: "NESDR SMArt v5 SDR bundle",
          image: "images/products/direct-core-kit.jpg",
          retailPrice: 65,
          priceDisplay: "$65",
          fulfillment: "dropship",
          stripeKey: "dsNesdrSmart",
          fulfillmentChannel: "direct_store",
          supplierUrl: "https://www.nooelec.com/store/nesdr-smart.html",
          amazonSearchUrl: "https://www.amazon.com/s?k=nooelec+nesdr+smart+v5",
          ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=nesdr+smart+v5",
          supplier: "NooElec",
          source: "dropship",
          description:
            "Budget RTL-SDR bundle with three antennas — HF/VHF/UHF receive lab companion for CyberThreatGotchi edge deployments. Receive-only; pair with Wireshark on a mirrored span or LAN Tap.",
          includes: ["NESDR SMArt v5", "3x antenna masts", "Aluminum enclosure", "Lab scope card"],
          badge: "SDR value",
        },
        {
          id: "ds-lan-tap",
          name: "Throwing Star LAN Tap Pro",
          image: "images/products/direct-core-kit.jpg",
          retailPrice: 59,
          priceDisplay: "$59",
          fulfillment: "dropship",
          stripeKey: "dsLanTap",
          fulfillmentChannel: "direct_store",
          supplierUrl: "https://shop.hak5.org/products/throwing-star-lan-tap-pro",
          amazonSearchUrl: "https://www.amazon.com/s?k=hak5+lan+tap+pro",
          supplier: "Hak5",
          source: "dropship",
          description:
            "Passive Ethernet tap for inline monitoring on authorized network segments — feeds tcpdump/Wireshark without injecting packets. Ideal companion for CTG edge IDS validation in your lab.",
          includes: ["Assembled LAN Tap Pro", "Passive monitor ports", "Field quick-start"],
          badge: "Network lab",
        },
        {
          id: "ds-throwing-star-kit",
          name: "Throwing Star LAN Tap solder kit",
          image: "images/products/direct-core-kit.jpg",
          retailPrice: 38,
          priceDisplay: "$38",
          fulfillment: "dropship",
          stripeKey: "dsThrowingStarKit",
          fulfillmentChannel: "direct_store",
          supplierUrl: "https://shop.hak5.org/products/throwing-star-lan-tap",
          supplier: "Hak5",
          source: "dropship",
          description:
            "DIY passive tap PCB kit — solder four RJ45 jacks and capacitors for homelab span monitoring. Same authorized-use scope as the assembled Pro; lower cost for makers who already bench solder.",
          includes: ["Tap PCB", "RJ45 jacks", "Capacitors", "Assembly guide link"],
        },
        {
          id: "ds-esp32-wifi-lab",
          name: "ESP32 WiFi lab dev board",
          image: "images/products/ds-esp32-lab.jpg",
          retailPrice: 45,
          priceDisplay: "$45",
          fulfillment: "dropship",
          stripeKey: "dsEsp32WifiLab",
          fulfillmentChannel: "direct_store",
          supplierUrl: "https://www.adafruit.com/product/3591",
          amazonSearchUrl: "https://www.amazon.com/s?k=adafruit+huzzah32+esp32",
          supplier: "Adafruit",
          source: "dropship",
          description:
            "Adafruit HUZZAH32 ESP32 Feather — dual-core WiFi/BT lab platform for authorized firmware experiments (monitor mode stacks, BLE survey). Not a turnkey Marauder build; pairs with our wiring kit.",
          includes: ["HUZZAH32 Feather", "USB serial", "Pinout card", "Authorized-lab README"],
          badge: "WiFi lab",
        },
        {
          id: "ds-usb-rubber-ducky",
          name: "USB Rubber Ducky training injector",
          image: "images/products/direct-core-kit.jpg",
          retailPrice: 129,
          priceDisplay: "$129",
          fulfillment: "dropship",
          stripeKey: "dsUsbRubberDucky",
          fulfillmentChannel: "direct_store",
          supplierUrl: "https://shop.hak5.org/products/usb-rubber-ducky",
          amazonSearchUrl: "https://www.amazon.com/s?k=hak5+usb+rubber+ducky",
          supplier: "Hak5",
          source: "dropship",
          description:
            "Hak5 USB Rubber Ducky — keystroke injection trainer for authorized physical-security and red-team education. Use only on systems you own or have written permission to test; DuckyScript payloads run in isolated lab VMs first.",
          includes: ["USB Rubber Ducky", "Payload Studio access info", "Authorized-use scope card"],
          badge: "Training",
        },
        {
          id: "ds-hak5-wifi-pineapple",
          name: "WiFi Pineapple Mark VII (authorized audit)",
          image: "images/products/ds-night-hunter.jpg",
          retailPrice: 319,
          priceDisplay: "$319",
          fulfillment: "dropship",
          stripeKey: "dsHak5WifiPineapple",
          fulfillmentChannel: "direct_store",
          supplierUrl: "https://shop.hak5.org/collections/wifi-pineapple",
          supplier: "Hak5",
          source: "dropship",
          description:
            "Industry-reference wireless audit platform for sanctioned red-team engagements — rogue AP assessment, captive portal tests, and PineAP recon on networks where you hold written authorization. Operator places Hak5 order manually after HPL checkout.",
          includes: ["WiFi Pineapple Mark VII base", "Antennas + USB-C power", "Engagement scope checklist"],
          badge: "Red team ref",
        },
      ],
    },
    {
      id: "authorized-lab-phones",
      label: "Lab phones",
      title: "Kali NetHunter | authorized mobile lab platforms",
      intro:
        "Pre-configured Android lab phones for authorized penetration testing education - sourced from specialist builders, not grey-market auto-checkout bots.",
      products: [
        {
          id: "ds-kali-nethunter",
          name: "Kali NetHunter lab phone (pre-flashed)",
          image: "images/products/ds-night-hunter.jpg",
          retailPrice: 399,
          priceDisplay: "$399",
          fulfillment: "dropship",
          stripeKey: "dsKaliNetHunter",
          supplierUrl: "https://kalinethunter.com/products",
          supplier: "KaliNetHunter.com / ViP3R Hunter",
          source: "dropship",
          description:
            "Handset prepared for authorized mobile security labs - Kali NetHunter with supported kernel where available. Model varies by stock (OnePlus, Pixel-class, or legacy Nexus tiers). We confirm device tier with you after checkout, then place the builder order manually.",
          includes: [
            "Pre-flashed NetHunter image",
            "USB data cable when supplied by builder",
            "Quick-start for authorized testing scope",
          ],
          badge: "Authorized lab",
        },
      ],
    },
    {
      id: "diy-stl",
      label: "DIY printables",
      title: "Free STL files | paid slicer packs",
      intro: "Download free community STLs or order digital KSS/SuperSlicer profile packs through checkout.",
      products: [
        {
          id: "ctg-stl-pack",
          name: "CyberThreatGotchi enclosure STLs",
          priceDisplay: "Free",
          source: "github",
          buyUrl: "https://github.com/salvador-Data/cyberThreatGotchi/tree/main/hardware/stl",
          description: "Front shell, rear shell, clip - e-ink and IPS display variants.",
          includes: ["ctg_front_shell.stl", "ctg_rear_shell.stl", "ctg_clip.stl"],
          badge: "Open source",
        },
        {
          id: "marauder-cyd-stl",
          name: "Marauder CYD case STLs",
          priceDisplay: "Free",
          source: "printables",
          buyUrl: "https://www.printables.com/model/1050109-esp32-marauder-cyd-cheap-yellow-display-28",
          description: "BlushTTV housing with GPS antenna cutout options.",
          includes: ["Top/bottom shell", "GPS slot", "Community remixes"],
        },
      ],
    },
  ],
};
