/**
 * Hacker Planet LLC - direct-ship products (made in Philadelphia)
 * fulfillment: "direct" - ships from HPL, not drop-shipped.
 * CYD hardware is separate from Mr. CrackBot AI Nano bench builds.
 */
window.HPL_DIRECT = {
  directNote: "Ships from Philadelphia, PA | 3-5 business days handling | tax & zone shipping extra",
  products: [
    {
      id: "cydStandard",
      section: "cyd",
      name: "CYD Field Build - Standard",
      tagline: "HPL signature profile",
      image: "images/products/direct-cyd-standard.jpg",
      retailPrice: 89.99,
      priceDisplay: "$89.99",
      fulfillment: "direct",
      stripeKey: "cydStandard",
      source: "direct",
      description:
        "Cheap Yellow Display pocket field build - flashed for authorized Wi-Fi lab work. Standard enclosure, USB-C, quick-start. **$89.99 + tax & shipping.** Not CrackBot firmware.",
      includes: ["CYD 2.8" display", "Printed enclosure", "HPL field image", "USB-C cable"],
      badge: "CYD standard",
    },
    {
      id: "cydFieldCustom",
      section: "cyd",
      name: "CYD Field Build - Custom",
      tagline: "Extended Wi-Fi/BLE | GPS | battery | power switch",
      image: "images/products/direct-marauder-custom.jpg",
      retailPrice: 189.99,
      priceDisplay: "$189.99",
      fulfillment: "direct",
      stripeKey: "cydFieldCustom",
      source: "direct",
      description:
        "Custom CYD with SMA antenna, extended Wi-Fi/BLE, GPS wardrive option, LiPo, and hardware on/off switch. Firmware profile (Marauder GPS, wardrive, etc.) at checkout. **$189.99 + tax & shipping.**",
      includes: ["Custom CYD stack", "GPS + antenna routing", "LiPo + switch", "Printed enclosure"],
      badge: "CYD custom",
    },
    {
      id: "crackbotBench",
      section: "crackbot",
      name: "Mr. CrackBot AI Nano - Bench Lab",
      tagline: "Jetson GPU hashcat | difficult assembly",
      image: "images/products/mr-pac-bot-product.png",
      retailPrice: 499,
      priceDisplay: "$499",
      fulfillment: "direct",
      stripeKey: "crackbotBench",
      source: "direct",
      description:
        "Full authorized lab build - Jetson Nano 4GB, monitor-mode USB Wi-Fi, CYD pocket UI in Mr. Pac-Bot shell, CrackBot firmware, GPU hashcat path. **Not** a CYD-only product. 4+ hour Philly assembly.",
      includes: [
        "Jetson Nano 4GB + carrier",
        "CYD UI in Mr. Pac-Bot shell",
        "USB Wi-Fi + LiPo",
        "CrackBot flash + burn-in",
      ],
      badge: "CrackBot bench",
    },
    {
      id: "remotePossibility",
      section: "cardputer",
      name: "Remote Possibility",
      tagline: "M5 Cardputer | universal IR remote",
      image: "images/products/direct-field-pack.png",
      retailPrice: 99.99,
      priceDisplay: "$99.99",
      fulfillment: "direct",
      stripeKey: "remotePossibility",
      source: "direct",
      description:
        "M5Stack Cardputer pre-flashed with Remote Possibility  - IR + RF 433 OOK + CC1101 sub-GHz profile library. Learn, scan TV/fan/AC, save remotes on SD. Module BOM in HARDWARE.md. Home and lab gear you own only.",
      includes: ["M5 Cardputer", "Remote Possibility firmware", "SD card", "IR/RF/CC1101 wiring guide"],
      badge: "Cardputer",
    },
    {
      id: "bleBot",
      section: "cardputer",
      name: "BLE Bot",
      tagline: "M5 Cardputer | authorized BLE scout",
      image: "images/products/direct-field-pack.png",
      retailPrice: 89.99,
      priceDisplay: "$89.99",
      fulfillment: "direct",
      stripeKey: "bleBot",
      source: "direct",
      description:
        "M5Stack Cardputer with BLE Bot firmware - keyboard-first BLE lab workflows for authorized research. Separate from CYD Wi-Fi field builds.",
      includes: ["M5 Cardputer", "BLE Bot firmware", "SD card", "Quick-start guide"],
      badge: "Cardputer",
    },
    {
      id: "coreKit",
      section: "ctg",
      name: "CyberThreatGotchi",
      image: "images/products/direct-core-kit.jpg",
      retailPrice: 219,
      priceDisplay: "$219",
      fulfillment: "direct",
      stripeKey: "coreKit",
      source: "direct",
      description:
        "Complete CyberThreatGotchi Cipherhorn build - BPI-R3 Mini 2 GB RAM (~$160 supplier floor), e-ink HAT, 3D enclosure, flashed SD, PSU, Philly flash and burn-in. Display variant (e-ink vs IPS) is the only hardware customization.",
      includes: ["BPI-R3 Mini (2 GB RAM)", "E-ink HAT", "Enclosure", "SD + PSU"],
      badge: "Popular",
    },
    {
      id: "fieldPack",
      section: "ctg",
      name: "Field Pack",
      image: "images/products/direct-field-pack.png",
      retailPrice: 279,
      priceDisplay: "$279",
      fulfillment: "direct",
      stripeKey: "fieldPack",
      source: "direct",
      description:
        "Desk + pocket bundle - Cipherhorn core kit plus M5Stack Cardputer (M5 OS) and printed quick-start. Saves vs buying core + Cardputer separately.",
      includes: ["Cipherhorn core", "M5 Cardputer + M5 OS", "Quick-start guide"],
    },
    {
      id: "boostFormulaCod",
      section: "other",
      name: "Boost Formula COD field kit",
      image: "images/products/direct-boost-formula.jpg",
      retailPrice: 99,
      priceDisplay: "$99",
      fulfillment: "direct",
      stripeKey: "boostFormulaCod",
      source: "direct",
      description:
        "ESP32-S3 COD field kit - Deauther-ready profile, external antenna, USB-C, tested in Philly. Firmware variant is the only customization; specify authorized-lab profile at checkout.",
      includes: ["ESP32-S3", "External antenna", "Pre-flashed lab image", "Quick-start card"],
    },
    {
      id: "codStlPack",
      section: "digital",
      name: "COD STL + KSS print pack",
      retailPrice: 19,
      priceDisplay: "$19",
      fulfillment: "digital",
      stripeKey: "codStlPack",
      source: "direct",
      description: "Digital delivery - pocket clip, wall dock, Prusa/SuperSlicer profiles.",
      includes: ["COD clip STL", "Wall dock STL", "KSS profiles"],
      badge: "Digital",
    },
    {
      id: "digital",
      section: "digital",
      name: "Digital Pack",
      retailPrice: 15,
      priceDisplay: "$15",
      fulfillment: "digital",
      stripeKey: "digital",
      source: "direct",
      description: "Full GitHub bundle, STL zip, sprites, marketing graphics - instant link.",
      includes: ["GitHub bundle", "STL zip", "Sprites", "Release PNGs"],
    },
  ],
};
