/**
 * Hacker Planet LLC — direct-ship products (made in Philadelphia)
 * fulfillment: "direct" — ships from HPL, not drop-shipped.
 */
window.HPL_DIRECT = {
  directNote: "Ships from Philadelphia, PA · 3–5 business days handling",
  products: [
    {
      id: "sabretoAkachi",
      name: "Sabreto Akachi",
      image: "images/products/direct-sabreto-akachi.jpg",
      retailPrice: 189,
      priceDisplay: "$189",
      fulfillment: "direct",
      stripeKey: "sabretoAkachi",
      source: "direct",
      description:
        "HackerPlanet signature CYD field build — Philly assembled. Customization is the only option: firmware profile, enclosure color, and antenna layout are configured to your lab brief at checkout.",
      includes: ["Custom CYD stack", "Printed enclosure", "Flashed lab image", "Quick-start card"],
      badge: "HPL original",
    },
    {
      id: "crackbotCyd",
      name: "Mr. CrackBot AI Nano on CYD",
      image: "images/products/direct-crackbot-cyd.jpg",
      retailPrice: 149,
      priceDisplay: "$149",
      fulfillment: "direct",
      stripeKey: "crackbotCyd",
      source: "direct",
      description:
        "Mr. CrackBot AI Nano on Cheap Yellow Display — pocket wordlist lab assistant, assembled in Philadelphia. Choose case color and wordlist pack scope; no other rendezvous options.",
      includes: ["CYD 2.8\" display", "CrackBot Nano firmware", "Case", "USB-C cable"],
      badge: "Ecosystem",
    },
    {
      id: "boostFormulaCod",
      name: "Boost Formula COD field kit",
      image: "images/products/direct-boost-formula.jpg",
      retailPrice: 99,
      priceDisplay: "$99",
      fulfillment: "direct",
      stripeKey: "boostFormulaCod",
      source: "direct",
      description:
        "ESP32-S3 COD field kit — Deauther-ready profile, external antenna, USB-C, tested in Philly. Firmware variant is the only customization; specify authorized-lab profile at checkout.",
      includes: ["ESP32-S3", "External antenna", "Pre-flashed lab image", "Quick-start card"],
    },
    {
      id: "marauderCustom175",
      name: "Marauder GPS field build",
      image: "images/products/direct-marauder-custom.jpg",
      retailPrice: 199,
      priceDisplay: "$199",
      fulfillment: "direct",
      stripeKey: "marauderCustom175",
      source: "direct",
      description:
        "Custom CYD Marauder with GPS wardrive, SMA antenna, LiPo, and printed enclosure + STL pack. Built to order in Philadelphia — enclosure color and GPS antenna routing are the configurable options.",
      includes: ["Full assembly", "GPS wardrive", "Printed enclosure", "STL files"],
      badge: "Custom build",
    },
    {
      id: "coreKit",
      name: "Cipherhorn Core Kit",
      image: "images/products/direct-core-kit.jpg",
      retailPrice: 169,
      priceDisplay: "$169",
      fulfillment: "direct",
      stripeKey: "coreKit",
      source: "direct",
      description:
        "CyberThreatGotchi Cipherhorn core — BPI-R3 Mini, e-ink HAT, 3D enclosure, flashed SD, PSU. Display variant (e-ink vs IPS) is the only hardware customization.",
      includes: ["BPI-R3 Mini", "E-ink HAT", "Enclosure", "SD + PSU"],
      badge: "Popular",
    },
    {
      id: "fieldPack",
      name: "Field Pack",
      image: "images/products/direct-field-pack.png",
      retailPrice: 219,
      priceDisplay: "$219",
      fulfillment: "direct",
      stripeKey: "fieldPack",
      source: "direct",
      description:
        "Desk + pocket bundle — Cipherhorn core kit plus M5Stack Cardputer and printed quick-start. Bundle is fixed; Cardputer accent color is the only optional customization.",
      includes: ["Cipherhorn core", "M5 Cardputer", "Quick-start guide"],
    },
    {
      id: "codStlPack",
      name: "COD STL + KSS print pack",
      retailPrice: 19,
      priceDisplay: "$19",
      fulfillment: "digital",
      stripeKey: "codStlPack",
      source: "direct",
      description: "Digital delivery — pocket clip, wall dock, Prusa/SuperSlicer profiles.",
      includes: ["COD clip STL", "Wall dock STL", "KSS profiles"],
      badge: "Digital",
    },
    {
      id: "digital",
      name: "Digital Pack",
      retailPrice: 15,
      priceDisplay: "$15",
      fulfillment: "digital",
      stripeKey: "digital",
      source: "direct",
      description: "Full repo assets, STL zip, sprites, marketing graphics — instant link.",
      includes: ["Repo bundle", "STL zip", "Sprites", "Release PNGs"],
    },
  ],
};
