/**
 * Hacker Planet LLC - drop-ship fulfillment tracker (operator config)
 *
 * Manual / semi-automated dropship only - no Etsy or AliExpress auto-charge.
 * Keys match stripeKey in catalog.config.js and payments.js.
 */
window.HPL_SHIPPING_TRACKER = {
  disclaimer:
    "Operator places supplier orders manually. Never store marketplace passwords in repo.",
  fulfillmentStatuses: [
    { id: "awaiting_payment", label: "Awaiting HPL payment confirmation" },
    { id: "ready_to_order", label: "Ready - place supplier order" },
    { id: "ordered", label: "Ordered at supplier" },
    { id: "shipped", label: "Shipped - tracking active" },
    { id: "delivered", label: "Delivered" },
    { id: "exception", label: "Exception / RMA" },
  ],
  channels: {
    etsy: {
      label: "Etsy",
      orderPortal: "https://www.etsy.com/your/purchases",
      trackingHint: "Use Etsy order confirmation -> carrier tracking link",
    },
    aliexpress: {
      label: "AliExpress",
      orderPortal: "https://www.aliexpress.com/p/order/index.html",
      trackingHint: "AliExpress order detail -> logistics tab",
    },
    tindie: {
      label: "Tindie",
      orderPortal: "https://www.tindie.com/accounts/orders/",
      trackingHint: "Tindie email -> carrier tracking",
    },
    direct_store: {
      label: "Supplier store",
      orderPortal: "",
      trackingHint: "Supplier confirmation email",
    },
    ebay: {
      label: "eBay",
      orderPortal: "https://www.ebay.com/mye/myebay/purchase",
      trackingHint: "eBay order detail -> View item -> tracking",
    },
    amazon: {
      label: "Amazon",
      orderPortal: "https://www.amazon.com/gp/your-account/order-history",
      trackingHint: "Amazon order -> Track package",
    },
  },
  trackingUrlTemplates: {
    usps: "https://tools.usps.com/go/TrackConfirmAction?tLabels={tracking}",
    ups: "https://www.ups.com/track?tracknum={tracking}",
    fedex: "https://www.fedex.com/fedextrack/?trknbr={tracking}",
    generic: "https://www.google.com/search?q={tracking}+package+tracking",
  },
  suppliers: {
    LayerFabUK: { channel: "etsy", region: "US", ratingNote: "Etsy Star Seller | Heltec V3 turnkey builds" },
    GarthVH: { channel: "etsy", region: "US", ratingNote: "Etsy Star Seller | Meshtastic / solar nodes" },
    OlleAdventures: { channel: "etsy", region: "US", ratingNote: "Netgotchi family" },
    ZitaoTech: { channel: "tindie", region: "EU/US", ratingNote: "Hackberry Pi cyberdecks" },
    HoneyHoneyTrading: { channel: "tindie", region: "US", ratingNote: "Marauder pocket builds" },
    CanaKit: { channel: "direct_store", region: "US", ratingNote: "Raspberry Pi authorized reseller kits" },
    PiShop: { channel: "direct_store", region: "US", ratingNote: "Raspberry Pi approved reseller" },
    SparkFun: { channel: "direct_store", region: "US", ratingNote: "Prototyping wire kits" },
    Adafruit: { channel: "direct_store", region: "US", ratingNote: "Breadboard + jumper bundles" },
    KaliNetHunterDevices: {
      channel: "direct_store",
      region: "US",
      ratingNote: "Pre-flashed NetHunter hardware - authorized testing only",
    },
    AliExpressVetted: { channel: "aliexpress", region: "CN->US", ratingNote: "Operator picks vetted seller per SKU" },
    eBayVetted: { channel: "ebay", region: "US", ratingNote: "Operator picks vetted US seller per SKU — manual checkout only" },
    LilyGO: { channel: "direct_store", region: "CN", ratingNote: "T-Beam boards" },
    Hak5: { channel: "direct_store", region: "US", ratingNote: "WiFi Pineapple, LAN Tap, USB Rubber Ducky — authorized lab framing" },
    NooElec: { channel: "direct_store", region: "US/CA", ratingNote: "RTL-SDR bundles — receive-only lab" },
    RTL-SDR Blog: { channel: "amazon", region: "US", ratingNote: "Official dongles via SparkFun / Amazon storefront" },
    RAKwireless: { channel: "direct_store", region: "US", ratingNote: "WisBlock Meshtastic kits" },
  },
  products: {
    dsMeshtasticHeltec: {
      supplier: "LayerFabUK",
      channel: "etsy",
      buildType: "fully_built",
      leadTimeDays: { min: 5, max: 14 },
      supplierCostUsd: 90,
      supplierUrl: "https://www.etsy.com/listing/1733234765/the-knight-complete-device-heltec-v3",
      ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=meshtastic+heltec+v3+built+case",
      orderChecklist: [
        "Confirm LoRa band (US 915 MHz default)",
        "Ship to customer address - not HPL warehouse unless forwarding",
        "Paste Etsy order ID into fulfillment log",
        "Message buyer preferences from Stripe order notes",
      ],
    },
    dsMeshtasticTBeam: {
      supplier: "LilyGO",
      channel: "direct_store",
      buildType: "kit",
      leadTimeDays: { min: 10, max: 21 },
      supplierCostUsd: 55,
      supplierUrl: "https://www.lilygo.cc/products/t-beam-v1-1",
      orderChecklist: ["Select correct LoRa band variant", "Include GPS module line item if split"],
    },
    dsMeshtasticRAK: {
      supplier: "RAKwireless",
      channel: "direct_store",
      buildType: "kit",
      leadTimeDays: { min: 7, max: 14 },
      supplierCostUsd: 85,
      supplierUrl: "https://store.rakwireless.com/products/wisblock-meshtastic-starter-kit",
      orderChecklist: ["Confirm WisBlock base size", "Note optional OLED/GNSS modules from customer"],
    },
    dsMeshtasticCase: {
      supplier: "GarthVH",
      channel: "etsy",
      buildType: "accessory",
      leadTimeDays: { min: 5, max: 12 },
      supplierCostUsd: 18,
      supplierUrl: "https://www.etsy.com/market/meshtastic_case",
      orderChecklist: ["Specify board model (Heltec V3 vs T-Beam)", "Confirm case color in Etsy message"],
    },
    dsKaliNetHunter: {
      supplier: "KaliNetHunterDevices",
      channel: "direct_store",
      buildType: "fully_built",
      leadTimeDays: { min: 7, max: 21 },
      supplierCostUsd: 280,
      supplierUrl: "https://kalinethunter.com/products",
      orderChecklist: [
        "Confirm device model and NetHunter tier with customer",
        "Include authorized-lab disclaimer in HPL shipment email",
        "Record IMEI only in secure ops log - never in git",
      ],
    },
    dsWiringLab: {
      supplier: "SparkFun",
      channel: "direct_store",
      buildType: "kit",
      leadTimeDays: { min: 3, max: 7 },
      supplierCostUsd: 14,
      supplierUrl: "https://www.sparkfun.com/jumper-wire-kit-140pcs.html",
      orderChecklist: ["Add Adafruit half-size breadboard if bundle out of stock", "Ship to customer directly"],
    },
    dsHackberryZero: {
      supplier: "ZitaoTech",
      channel: "tindie",
      buildType: "fully_built",
      leadTimeDays: { min: 10, max: 21 },
      supplierCostUsd: 165,
      supplierUrl: "https://www.elecrow.com/hackberrypi-zero-with-q10-keyboard.html",
      orderChecklist: ["Confirm keyboard variant (Q10/Q20/9900)", "Pi Zero 2 W often sold separately - verify listing"],
    },
    dsHackberryPi5: {
      supplier: "ZitaoTech",
      channel: "tindie",
      buildType: "deck_shell",
      leadTimeDays: { min: 14, max: 28 },
      supplierCostUsd: 280,
      supplierUrl: "https://www.tindie.com/products/zitaotech/hackberrypi5-with-9900-keyboard/",
      orderChecklist: ["Deck ships without Pi 5 - note if customer expects full SBC", "Confirm keyboard option"],
    },
    dsHackberryCM5: {
      supplier: "ZitaoTech",
      channel: "tindie",
      buildType: "deck_shell",
      leadTimeDays: { min: 14, max: 28 },
      supplierCostUsd: 320,
      supplierUrl: "https://github.com/ZitaoTech/HackberryPiCM5",
      orderChecklist: ["Order via Tindie/Elecrow when in stock", "CM5 module typically customer-supplied"],
    },
    dsRaspberryPi5: {
      supplier: "eBayVetted",
      channel: "ebay",
      buildType: "kit",
      leadTimeDays: { min: 5, max: 10 },
      supplierCostUsd: 105,
      supplierUrl: "https://www.canakit.com/raspberry-pi-5.html",
      ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=raspberry+pi+5+8gb+starter+kit",
      orderChecklist: [
        "Prefer authorized reseller when in stock; eBay fallback for partner fulfillment",
        "Confirm 4GB vs 8GB RAM",
      ],
    },
    dsEsp32Cyd: {
      supplier: "eBayVetted",
      channel: "ebay",
      buildType: "module",
      leadTimeDays: { min: 7, max: 14 },
      supplierCostUsd: 28,
      supplierUrl: "https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display",
      ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=esp32-2432S028R+cheap+yellow+display",
      orderChecklist: [
        "Order ESP32-2432S028R variant (resistive touch)",
        "Verify ILI9341 controller in listing photos",
        "Quantity 2 per HPL line item",
      ],
    },
    dsPwnagotchi: {
      supplier: "eBayVetted",
      channel: "ebay",
      buildType: "fully_built",
      leadTimeDays: { min: 7, max: 14 },
      supplierCostUsd: 115,
      supplierUrl: "https://www.etsy.com/market/pwnagotchi",
      ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=pwnagotchi+assembled+oled",
      orderChecklist: [
        "Match customer board preference in seller message",
        "Etsy GarthVH fallback if eBay listing quality is low",
      ],
    },
    dsNetgotchi: {
      supplier: "OlleAdventures",
      channel: "etsy",
      buildType: "fully_built",
      leadTimeDays: { min: 5, max: 12 },
      supplierCostUsd: 65,
      supplierUrl: "https://olleadventures.etsy.com/listing/1752764124",
      ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=netgotchi+defensive",
      orderChecklist: ["Case color: black or blue per order notes", "eBay fallback only if Etsy OOS"],
    },
    dsNetgotchiPro: {
      supplier: "OlleAdventures",
      channel: "etsy",
      buildType: "fully_built",
      leadTimeDays: { min: 5, max: 12 },
      supplierCostUsd: 85,
      supplierUrl: "https://olleadventures.etsy.com/listing/1771783598",
      orderChecklist: ["Case color in Etsy checkout message"],
    },
    dsNightHunter: {
      supplier: "HoneyHoneyTrading",
      channel: "tindie",
      buildType: "fully_built",
      leadTimeDays: { min: 7, max: 14 },
      supplierCostUsd: 145,
      supplierUrl: "https://www.tindie.com/products/honeyhoneytrading/esp32-marauder-pocket-unit-with-gps-v2/",
      orderChecklist: ["Enclosure color from customer notes"],
    },
    dsMarauderGps: {
      supplier: "HoneyHoneyTrading",
      channel: "tindie",
      buildType: "fully_built",
      leadTimeDays: { min: 7, max: 14 },
      supplierCostUsd: 155,
      supplierUrl: "https://www.tindie.com/products/honeyhoneytrading/esp32-marauder-pocket-unit-with-gps-v2/",
      orderChecklist: ["Same SKU as Night Hunter - verify customer intent"],
    },
    dsMarauderBatteryMod: {
      supplier: "BiscuitShop",
      channel: "direct_store",
      buildType: "kit",
      leadTimeDays: { min: 5, max: 10 },
      supplierCostUsd: 38,
      supplierUrl: "https://biscuitshop.us/products/esp32-marauder-battery-mod-kit",
      orderChecklist: ["CYD board not included - customer may already own CYD"],
    },
    dsMarauderKoko: {
      supplier: "JustCallMeKoko",
      channel: "tindie",
      buildType: "kit",
      leadTimeDays: { min: 7, max: 14 },
      supplierCostUsd: 58,
      supplierUrl: "https://www.tindie.com/products/justcallmekoko/esp32-marauder-kit/",
      orderChecklist: ["Customer supplies ESP32 Huzzah32 + LiPo"],
    },
    dsOrangePi5: {
      supplier: "eBayVetted",
      channel: "ebay",
      buildType: "kit",
      leadTimeDays: { min: 7, max: 21 },
      supplierCostUsd: 78,
      supplierUrl: "https://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5-plus.html",
      ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=orange+pi+5+plus+8gb",
      orderChecklist: ["Confirm 8GB RAM listing", "Prefer official Orange Pi store when available"],
    },
    dsBananaPiR3: {
      supplier: "eBayVetted",
      channel: "ebay",
      buildType: "kit",
      leadTimeDays: { min: 7, max: 21 },
      supplierCostUsd: 160,
      supplierUrl: "https://www.banana-pi.org/",
      ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=banana+pi+bpi-r3+mini+2gb",
      orderChecklist: [
        "Ops spare board only — CTG coreKit component",
        "Confirm 2 GB RAM / 8 GB eMMC Mini variant",
        "Reject gray-market <$100 listings for customer-facing orders",
      ],
    },
    dsRtlSdrKit: {
      supplier: "RTL-SDR Blog",
      channel: "amazon",
      buildType: "kit",
      leadTimeDays: { min: 3, max: 10 },
      supplierCostUsd: 85,
      supplierUrl: "https://www.sparkfun.com/rtl-sdr-blog-v3-usb-dongle-with-dipole-antenna-kit.html",
      amazonSearchUrl: "https://www.amazon.com/s?k=rtl-sdr+blog+v3+dipole+antenna+kit",
      ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=rtl-sdr+blog+v3+dipole",
      orderChecklist: [
        "Prefer SparkFun or RTL-SDR Blog Amazon seller",
        "Receive-only lab — document authorized scope in shipment email",
      ],
    },
    dsNesdrSmart: {
      supplier: "NooElec",
      channel: "direct_store",
      buildType: "kit",
      leadTimeDays: { min: 5, max: 12 },
      supplierCostUsd: 52,
      supplierUrl: "https://www.nooelec.com/store/nesdr-smart.html",
      amazonSearchUrl: "https://www.amazon.com/s?k=nooelec+nesdr+smart+v5",
      ebaySearchUrl: "https://www.ebay.com/sch/i.html?_nkw=nesdr+smart+v5",
      orderChecklist: ["Confirm v5 bundle with three antennas", "Ship direct to customer"],
    },
    dsLanTap: {
      supplier: "Hak5",
      channel: "direct_store",
      buildType: "accessory",
      leadTimeDays: { min: 5, max: 12 },
      supplierCostUsd: 45,
      supplierUrl: "https://shop.hak5.org/products/throwing-star-lan-tap-pro",
      amazonSearchUrl: "https://www.amazon.com/s?k=hak5+lan+tap+pro",
      orderChecklist: [
        "Passive tap only — customer must own monitored network segment",
        "Include Wireshark/tcpdump quick-start link",
      ],
    },
    dsThrowingStarKit: {
      supplier: "Hak5",
      channel: "direct_store",
      buildType: "kit",
      leadTimeDays: { min: 5, max: 12 },
      supplierCostUsd: 20,
      supplierUrl: "https://shop.hak5.org/products/throwing-star-lan-tap",
      orderChecklist: ["Customer soldered kit — confirm they accept DIY assembly"],
    },
    dsEsp32WifiLab: {
      supplier: "Adafruit",
      channel: "direct_store",
      buildType: "module",
      leadTimeDays: { min: 3, max: 8 },
      supplierCostUsd: 28,
      supplierUrl: "https://www.adafruit.com/product/3591",
      amazonSearchUrl: "https://www.amazon.com/s?k=adafruit+huzzah32+esp32",
      orderChecklist: ["HUZZAH32 pre-soldered headers variant", "Authorized WiFi lab scope card in package"],
    },
    dsUsbRubberDucky: {
      supplier: "Hak5",
      channel: "direct_store",
      buildType: "fully_built",
      leadTimeDays: { min: 5, max: 12 },
      supplierCostUsd: 100,
      supplierUrl: "https://shop.hak5.org/products/usb-rubber-ducky",
      amazonSearchUrl: "https://www.amazon.com/s?k=hak5+usb+rubber+ducky",
      orderChecklist: [
        "Training injector — owned systems / written scope only",
        "Never ship pre-loaded offensive payloads without customer sign-off",
      ],
    },
    dsHak5WifiPineapple: {
      supplier: "Hak5",
      channel: "direct_store",
      buildType: "fully_built",
      leadTimeDays: { min: 7, max: 14 },
      supplierCostUsd: 250,
      supplierUrl: "https://shop.hak5.org/collections/wifi-pineapple",
      orderChecklist: [
        "Confirm written red-team authorization on file",
        "Basic Mark VII tier unless customer ordered Enterprise",
        "Include engagement scope + authorized-use disclaimer",
      ],
    },
  },
};
