#!/usr/bin/env bash
# ctg-lab-ap-setup.sh — CTG-UTMS-LAB soft AP profile (authorized isolated lab only).
# DiagnoseOnly by default. --apply requires /etc/ctg/lab-wifi.conf and --i-understand-lab-only.
# NEVER evil twin, NEVER credential captive portal, NEVER spoof production SSIDs.
set -euo pipefail

SCRIPT_NAME="$(basename "$0")"
LAB_CONF="/etc/ctg/lab-wifi.conf"
HOSTAPD_CONF="/etc/ctg/hostapd-lab.conf"
AP_SSID="${CTG_LAB_AP_SSID:-CTG-UTMS-LAB}"
AP_VLAN="${CTG_LAB_AP_VLAN:-99}"
DIAGNOSE_ONLY=true
APPLY=false
LAB_ACK=false

usage() {
  cat <<EOF
Usage: sudo $SCRIPT_NAME [options]

Isolated lab soft AP on Kali (hostapd profile). Defensive training AP only.

Options:
  --diagnose                 Report prerequisites (default)
  --apply                    Write hostapd stub + nmcli hints (requires lab-wifi.conf)
  --i-understand-lab-only    Required with --apply (explicit lab-only acknowledgment)
  -h                         Help

Requires: /etc/ctg/lab-wifi.conf (600) from lab-wifi.conf.example — placeholders only in git.
See docs/LAB_AP_UTMS.md
EOF
}

log_msg() {
  printf '%s %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

require_root() {
  [[ "${EUID:-$(id -u)}" -ne 0 ]] && { echo "Run as root: sudo $SCRIPT_NAME" >&2; exit 1; }
}

diagnose() {
  log_msg "--- CTG lab AP diagnose (no changes) ---"
  if [[ -f "$LAB_CONF" ]]; then
    log_msg "OK: $LAB_CONF exists (mode $(stat -c '%a' "$LAB_CONF" 2>/dev/null || echo ?))"
  else
    log_msg "WARN: $LAB_CONF missing — copy from lab-wifi.conf.example on share"
  fi
  for cmd in hostapd iw nmcli; do
    if command -v "$cmd" >/dev/null 2>&1; then
      log_msg "OK: $cmd"
    else
      log_msg "WARN: $cmd not installed"
    fi
  done
  log_msg "Planned SSID: $AP_SSID (isolated lab — not production clone)"
  log_msg "VLAN tag (conceptual): $AP_VLAN — tie to OPNSENSE/homelab doc"
  log_msg "Legal: authorized lab AP only; no evil twin; FCC part 15 unlicensed limits apply"
}

write_hostapd_stub() {
  mkdir -p /etc/ctg
  # shellcheck source=/dev/null
  source "$LAB_CONF"
  local psk="${LAB_WIFI_PSK:-your-psk}"
  cat >"$HOSTAPD_CONF" <<EOF
# CTG-UTMS-LAB — generated by $SCRIPT_NAME — authorized lab only
interface=${LAB_WIFI_IFACE:-wlan0}
driver=nl80211
ssid=${AP_SSID}
hw_mode=g
channel=${LAB_WIFI_CHANNEL:-6}
wpa=2
wpa_passphrase=${psk}
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
ieee80211w=2
EOF
  chmod 600 "$HOSTAPD_CONF"
  log_msg "Wrote $HOSTAPD_CONF (600). Start manually: hostapd $HOSTAPD_CONF"
  log_msg "Do NOT reuse home/production SSID names."
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --diagnose) DIAGNOSE_ONLY=true; APPLY=false; shift ;;
    --apply) APPLY=true; DIAGNOSE_ONLY=false; shift ;;
    --i-understand-lab-only) LAB_ACK=true; shift ;;
    -h) usage; exit 0 ;;
    *) echo "Unknown: $1" >&2; usage; exit 1 ;;
  esac
done

require_root

if [[ "$APPLY" == true ]]; then
  [[ "$LAB_ACK" == true ]] || { log_msg "ERROR: --apply requires --i-understand-lab-only"; exit 1; }
  [[ -f "$LAB_CONF" ]] || { log_msg "ERROR: $LAB_CONF required"; exit 1; }
  write_hostapd_stub
  exit 0
fi

diagnose
