/**
 * Hacker Planet LLC — drop-ship catalog (retail prices)
 *
 * Customer pays HPL via Stripe → you order from supplierUrl → ships to customer.
 * supplierUrl is for your fulfillment ops (also in docs/DROPSHIP_CATALOG.md).
 */
window.HPL_CATALOG = {
  dropshipNote: "Drop-ship · 5–14 business days · authorized lab use only",
  affiliate: {
    aliexpress: "",
    etsy: "",
    tindie: "",
  },
  sections: [
    {
      id: "gotchi-pods",
      label: "Gotchi & wardrive pods",
      title: "Pwnagotchi · Netgotchi · night-hunter field pods",
      intro:
        "Tamagotchi-style WiFi lab devices — assembled builds drop-shipped from verified makers. Mid-range Kali-ready configs available on request.",
      products: [
        {
          id: "ds-pwnagotchi",
          name: "Pwnagotchi — assembled wardrive pod",
          image: "images/products/ds-pwnagotchi.png",
          retailPrice: 169,
          priceDisplay: "$169",
          fulfillment: "dropship",
          stripeKey: "dsPwnagotchi",
          supplierUrl: "https://www.etsy.com/market/pwnagotchi",
          supplier: "Etsy / community makers",
          source: "dropship",
          description:
            "Community-assembled Pi Zero W or ESP32 wardrive pod with OLED Tamagotchi face — passive WiFi observation for authorized labs. Board, face theme, and enclosure vary by maker; tell us your preferences at checkout and we route to a matching Etsy build.",
          includes: ["Flashed SD image", "OLED face", "Pi Zero W or ESP base", "USB power cable"],
          badge: "Wardrive",
        },
        {
          id: "ds-netgotchi",
          name: "Netgotchi — defensive network guardian",
          image: "images/products/ds-netgotchi.jpg",
          retailPrice: 99,
          priceDisplay: "$99",
          fulfillment: "dropship",
          stripeKey: "dsNetgotchi",
          supplierUrl: "https://olleadventures.etsy.com/listing/1752764124",
          supplier: "OlleAdventures",
          source: "dropship",
          description:
            "NETGOTCHI v2 from OlleAdventures — Pwnagotchi's defensive sibling: honeypot, intrusion alerts, and periodic 2.4 GHz WiFi scans. Expandable case with OLED and speaker; open-source firmware on GitHub. Case color is the only customization — message your preference (default black or blue) at checkout.",
          includes: ["Assembled board + case", "OLED + speaker", "Micro USB cable", "Open-source firmware"],
          badge: "Defensive",
        },
        {
          id: "ds-netgotchi-pro",
          name: "Netgotchi Pro — keypad + buzzer",
          image: "images/products/ds-netgotchi-pro.jpg",
          retailPrice: 129,
          priceDisplay: "$129",
          fulfillment: "dropship",
          stripeKey: "dsNetgotchiPro",
          supplierUrl: "https://olleadventures.etsy.com/listing/1771783598",
          supplier: "OlleAdventures",
          source: "dropship",
          description:
            "NETGOTCHI PRO — portable network guardian with keypad, buzzer, TEXTgotchi mode, and on-device settings. Scans and protects 2.4 GHz networks; expandable case. Customization is case color only — note your choice at checkout.",
          includes: ["Keypad + buzzer", "Expandable case", "OLED + speaker", "USB cable"],
        },
        {
          id: "ds-night-hunter",
          name: "Night Hunter pod — Kali-ready field build",
          image: "images/products/ds-night-hunter.jpg",
          retailPrice: 189,
          priceDisplay: "$189",
          fulfillment: "dropship",
          stripeKey: "dsNightHunter",
          supplierUrl: "https://www.tindie.com/products/honeyhoneytrading/esp32-marauder-pocket-unit-with-gps-v2/",
          supplier: "HoneyHoneyTrading",
          source: "dropship",
          description:
            "ESP32 Marauder Pocket Unit with GPS v2 — 2.8\" touchscreen, dual SMA WiFi/BT antennas, wardrive GPS, dual 18650 bays, SD PCAP storage, and 3D-printed enclosure (~9.2×4.6×7.1 cm). Enclosure color is the listing customization; we pass your choice to HoneyHoneyTrading.",
          includes: ["CYD 2.8\" touchscreen", "GPS + dual SMA", "8GB SD", "Printed enclosure"],
          badge: "Kali-ready",
        },
      ],
    },
    {
      id: "meshtastic",
      label: "Meshtastic",
      title: "Meshtastic mesh radio kits",
      intro:
        "Off-grid LoRa mesh nodes — drop-shipped from LilyGO, Heltec, and RAK suppliers. Flash Meshtastic firmware for field comms.",
      products: [
        {
          id: "ds-meshtastic-tbeam",
          name: "LilyGO T-Beam v1.1 Meshtastic kit",
          image: "images/products/ds-meshtastic-tbeam.png",
          retailPrice: 89,
          priceDisplay: "$89",
          fulfillment: "dropship",
          stripeKey: "dsMeshtasticTBeam",
          supplierUrl: "https://www.lilygo.cc/products/t-beam-v1-1",
          supplier: "LilyGO / AliExpress",
          source: "dropship",
          description:
            "Classic Meshtastic backpack node — ESP32 + SX1276 LoRa + GPS, battery holder, and antenna. LilyGO ships multiple LoRa band options; tell us your region at checkout and we order the matching band.",
          includes: ["T-Beam v1.1 board", "GPS module", "LoRa antenna", "Battery holder"],
          badge: "LoRa mesh",
        },
        {
          id: "ds-meshtastic-heltec",
          name: "Heltec V3 Meshtastic node",
          image: "images/products/ds-meshtastic-heltec.jpg",
          retailPrice: 79,
          priceDisplay: "$79",
          fulfillment: "dropship",
          stripeKey: "dsMeshtasticHeltec",
          supplierUrl: "https://heltec.org/project/wifi-lora-32-v3/",
          supplier: "Heltec",
          source: "dropship",
          description:
            "WiFi LoRa 32 (V3) — ESP32-S3 + SX1262 with onboard OLED, Meshtastic and LoRaWAN compatible. Choose LoRa band (433/470/863/902 MHz) and optional plastic shell on the supplier listing; we place the variant you specify.",
          includes: ["Heltec V3 board", "LoRa antenna", "USB-C cable"],
        },
        {
          id: "ds-meshtastic-rak",
          name: "RAK4631 Meshtastic starter kit",
          image: "images/products/ds-meshtastic-rak.webp",
          retailPrice: 119,
          priceDisplay: "$119",
          fulfillment: "dropship",
          stripeKey: "dsMeshtasticRAK",
          supplierUrl: "https://store.rakwireless.com/products/wisblock-meshtastic-starter-kit",
          supplier: "RAKwireless",
          source: "dropship",
          description:
            "WisBlock Meshtastic Starter Kit — RAK4631 (nRF52840 + SX1262) pre-flashed, 2 dBi rubber antenna, BLE antenna, USB cable. Pick base board size and optional OLED/GNSS modules on RAKwireless; customization is module mix only.",
          includes: ["RAK4631 core (Meshtastic FW)", "WisBlock base", "2 dBi LoRa antenna", "USB cable"],
          badge: "Starter",
        },
        {
          id: "ds-meshtastic-case",
          name: "Meshtastic 3D-printed field case",
          retailPrice: 34,
          priceDisplay: "$34",
          fulfillment: "dropship",
          stripeKey: "dsMeshtasticCase",
          supplierUrl: "https://www.etsy.com/search?q=meshtastic+case+3d+print",
          supplier: "Etsy makers",
          source: "dropship",
          description: "Weather-resistant printed enclosure for T-Beam or Heltec — maker drop-ship.",
          includes: ["Printed top/bottom", "Mounting hardware", "Antenna passthrough"],
        },
      ],
    },
    {
      id: "hackberry",
      label: "Hackberry Pi",
      title: "Hackberry Pi cyberdecks (ZitaoTech)",
      intro:
        "BlackBerry-keyboard Linux handhelds — Kali-ready cyberdecks drop-shipped from ZitaoTech / community distributors.",
      products: [
        {
          id: "ds-hackberry-zero",
          name: "Hackberry Pi Zero — pocket Kali terminal",
          image: "images/products/ds-hackberry-zero.png",
          retailPrice: 279,
          priceDisplay: "$279",
          fulfillment: "dropship",
          stripeKey: "dsHackberryZero",
          supplierUrl: "https://github.com/ZitaoTech/Hackberry-Pi_Zero",
          supplier: "ZitaoTech",
          source: "dropship",
          description:
            "Handheld Linux terminal — Raspberry Pi Zero 2 W, 720×720 TFT, BlackBerry keyboard (Q10/Q20/9900), three USB ports, swappable Nokia BL-5C cells. Keyboard layout is the main supplier customization.",
          includes: ["Assembled deck", "BB keyboard", "Batteries", "Type-C charge"],
          badge: "Cyberdeck",
        },
        {
          id: "ds-hackberry-pi5",
          name: "Hackberry Pi 5 — full cyberdeck",
          image: "images/products/ds-hackberry-pi5.png",
          retailPrice: 449,
          priceDisplay: "$449",
          fulfillment: "dropship",
          stripeKey: "dsHackberryPi5",
          supplierUrl: "https://github.com/ZitaoTech/HackberryPi5",
          supplier: "ZitaoTech",
          source: "dropship",
          description:
            "Pi 5 cyberdeck with 720×720 touch display, dual 18650 power, stereo Bluetooth speakers, VIAL keymaps, Stemma I2C — runs Kali or Raspberry Pi OS. Keyboard and plate options are configured with ZitaoTech.",
          includes: ["Pi 5 slot build", "720×720 touch", "Stereo BT speakers", "Stemma I2C"],
        },
        {
          id: "ds-hackberry-cm5",
          name: "Hackberry Pi CM5 — ultra portable",
          image: "images/products/ds-hackberry-cm5.png",
          retailPrice: 499,
          priceDisplay: "$499",
          fulfillment: "dropship",
          stripeKey: "dsHackberryCM5",
          supplierUrl: "https://github.com/ZitaoTech/HackberryPiCM5",
          supplier: "ZitaoTech",
          source: "dropship",
          description:
            "CM5 compute module in aluminium body — NVMe slot, USB 3, HDMI out, dual speakers. Ultra-portable pro deck; enclosure and keymap are the configurable options from ZitaoTech.",
          includes: ["CM5-compatible shell", "Dual speakers", "Metal plates", "3D mid-frame"],
          badge: "Pro",
        },
      ],
    },
    {
      id: "marauder-wifi",
      label: "Marauder & WiFi lab",
      title: "ESP32 Marauder · Deauther · custom builds",
      intro: "Authorized RF lab tools — GPS wardrive builds and battery mods drop-shipped from partner makers.",
      products: [
        {
          id: "ds-marauder-gps",
          name: "Marauder pocket + GPS v2",
          image: "images/products/ds-marauder-gps.jpg",
          retailPrice: 219,
          priceDisplay: "$219",
          fulfillment: "dropship",
          stripeKey: "dsMarauderGps",
          supplierUrl: "https://www.tindie.com/products/honeyhoneytrading/esp32-marauder-pocket-unit-with-gps-v2/",
          supplier: "HoneyHoneyTrading",
          source: "dropship",
          description:
            "HoneyHoneyTrading ESP32 Marauder Pocket with GPS v2 — wardrive logging, dual SMA antennas, 8GB SanDisk SD, 2.8\" CYD touchscreen, dual 18650 (batteries not shipped). Case color is the only customization on the listing.",
          includes: ["GPS module", "WiFi/BT antennas", "8GB SD", "USB-C charge"],
        },
        {
          id: "ds-marauder-battery",
          name: "CYD battery + GPS mod kit",
          image: "images/products/ds-marauder-battery.jpg",
          retailPrice: 59,
          priceDisplay: "$59",
          fulfillment: "dropship",
          stripeKey: "dsMarauderBatteryMod",
          supplierUrl: "https://biscuitshop.us/products/esp32-marauder-battery-mod-kit",
          supplier: "Biscuit Shop",
          source: "dropship",
          description:
            "Biscuit Shop V2 drop-in PCB for Cheap Yellow Display — no soldering, adds LiPo power, I2C fuel gauge, and GPS for Marauder wardrive builds.",
          includes: ["GPS antenna", "Charge circuit", "Plug-in PCB"],
        },
        {
          id: "ds-marauder-koko",
          name: "Official Marauder Kit (Koko PCB)",
          image: "images/products/ds-marauder-koko.jpg",
          retailPrice: 89,
          priceDisplay: "$89",
          fulfillment: "dropship",
          stripeKey: "dsMarauderKoko",
          supplierUrl: "https://www.tindie.com/products/justcallmekoko/esp32-marauder-kit/",
          supplier: "JustCallMeKoko",
          source: "dropship",
          description:
            "JustCallMeKoko official ESP32 Marauder kit — PCB and 3D-printed enclosure; you supply Huzzah32 and LiPo. Portable WiFi/BT analysis firmware.",
          includes: ["PCB", "3D printed case", "Screws", "QR docs"],
        },
      ],
    },
    {
      id: "sbc-hacker",
      label: "SBC & Pi kits",
      title: "Raspberry Pi · Orange Pi · edge router boards",
      intro: "Mid-range hacker SBC kits drop-shipped from AliExpress / official distributors — vetted sellers only.",
      products: [
        {
          id: "ds-rpi5-kit",
          name: "Raspberry Pi 5 starter kit (8GB class)",
          retailPrice: 139,
          priceDisplay: "$139",
          fulfillment: "dropship",
          stripeKey: "dsRaspberryPi5",
          supplierUrl: "https://www.aliexpress.com/w/wholesale-raspberry-pi-5-kit.html",
          supplier: "AliExpress (vetted seller)",
          source: "dropship",
          description: "Pi 5 board + heatsink + 27W PSU + case — homelab IDS or CyberThreatGotchi dev bench.",
          includes: ["Pi 5 board", "Active cooler", "Power supply", "Case"],
        },
        {
          id: "ds-orange-pi5",
          name: "Orange Pi 5 Plus (8GB) kit",
          retailPrice: 119,
          priceDisplay: "$119",
          fulfillment: "dropship",
          stripeKey: "dsOrangePi5",
          supplierUrl: "https://www.aliexpress.com/w/wholesale-orange-pi-5-plus.html",
          supplier: "AliExpress / Orange Pi store",
          source: "dropship",
          description: "RK3588 SBC for lightweight SIEM edges and portable lab stacks.",
          includes: ["8GB RAM variant", "Heatsink", "Power adapter"],
        },
        {
          id: "ds-bpi-r3",
          name: "Banana Pi BPI-R3 Mini router SBC",
          retailPrice: 109,
          priceDisplay: "$109",
          fulfillment: "dropship",
          stripeKey: "dsBananaPiR3",
          supplierUrl: "https://www.aliexpress.com/w/wholesale-banana-pi-r3-mini.html",
          supplier: "AliExpress",
          source: "dropship",
          description: "Same class as CyberThreatGotchi core — dual 2.5G Ethernet, Wi-Fi 6.",
          includes: ["BPI-R3 Mini", "Antennas", "Optional case"],
          badge: "Edge IPS",
        },
        {
          id: "ds-esp32-lab",
          name: "ESP32 CYD lab bundle (×2 boards)",
          retailPrice: 49,
          priceDisplay: "$49",
          fulfillment: "dropship",
          stripeKey: "dsEsp32Cyd",
          supplierUrl: "https://www.aliexpress.com/w/wholesale-esp32-2432s028.html",
          supplier: "AliExpress",
          source: "dropship",
          description: "Two Cheap Yellow Display boards for Marauder, Bruce, or firmware dev spares.",
          includes: ["2× CYD 2.8\"", "USB cables", "Basic antennas"],
        },
      ],
    },
    {
      id: "diy-stl",
      label: "DIY printables",
      title: "Free STL files · paid slicer packs",
      intro: "Download free community STLs or order digital KSS/SuperSlicer profile packs through checkout.",
      products: [
        {
          id: "ctg-stl-pack",
          name: "CyberThreatGotchi enclosure STLs",
          priceDisplay: "Free",
          source: "github",
          buyUrl: "https://github.com/salvador-Data/cyberThreatGotchi/tree/main/hardware/stl",
          description: "Front shell, rear shell, clip — e-ink and IPS display variants.",
          includes: ["ctg_front_shell.stl", "ctg_rear_shell.stl", "ctg_clip.stl"],
          badge: "Open source",
        },
        {
          id: "marauder-cyd-stl",
          name: "Marauder CYD case STLs",
          priceDisplay: "Free",
          source: "printables",
          buyUrl: "https://www.printables.com/model/1050109-esp32-marauder-cyd-cheap-yellow-display-28",
          description: "BlushTTV housing with GPS antenna cutout options.",
          includes: ["Top/bottom shell", "GPS slot", "Community remixes"],
        },
      ],
    },
  ],
};
