/**
 * Hacker Planet LLC — direct-ship products (made in Philadelphia)
 * fulfillment: "direct" — ships from HPL, not drop-shipped.
 */
window.HPL_DIRECT = {
  directNote: "Ships from Philadelphia, PA · 3–5 business days handling",
  products: [
    {
      id: "sabretoAkachi",
      name: "Sabreto Akachi",
      retailPrice: 189,
      priceDisplay: "$189",
      fulfillment: "direct",
      stripeKey: "sabretoAkachi",
      source: "direct",
      description:
        "Hacker Planet signature field build — custom CYD assembly tuned for authorized edge-lab work.",
      includes: ["Custom CYD stack", "Printed enclosure", "Flashed lab image", "Quick-start card"],
      badge: "HPL original",
    },
    {
      id: "crackbotCyd",
      name: "Mr. CrackBot AI Nano on CYD",
      retailPrice: 149,
      priceDisplay: "$149",
      fulfillment: "direct",
      stripeKey: "crackbotCyd",
      source: "direct",
      description:
        "CrackBot wordlist lab on Cheap Yellow Display — pocket password research assistant, Philly assembled.",
      includes: ["CYD 2.8\" display", "CrackBot Nano firmware", "Case", "USB-C cable"],
      badge: "Ecosystem",
    },
    {
      id: "boostFormulaCod",
      name: "Boost Formula COD field kit",
      retailPrice: 99,
      priceDisplay: "$99",
      fulfillment: "direct",
      stripeKey: "boostFormulaCod",
      source: "direct",
      description: "ESP32-S3 Deauther-ready profile, antenna, USB-C — assembled and tested in Philly.",
      includes: ["ESP32-S3", "External antenna", "Pre-flashed lab image", "Quick-start card"],
    },
    {
      id: "marauderCustom175",
      name: "Marauder GPS field build",
      retailPrice: 199,
      priceDisplay: "$199",
      fulfillment: "direct",
      stripeKey: "marauderCustom175",
      source: "direct",
      description: "CYD Marauder with GPS wardrive, SMA antenna, LiPo, printed enclosure + STL pack.",
      includes: ["Full assembly", "GPS wardrive", "Printed enclosure", "STL files"],
      badge: "Custom build",
    },
    {
      id: "coreKit",
      name: "Cipherhorn Core Kit",
      retailPrice: 169,
      priceDisplay: "$169",
      fulfillment: "direct",
      stripeKey: "coreKit",
      source: "direct",
      description: "BPI-R3 Mini + e-ink HAT + 3D enclosure + flashed SD + PSU.",
      includes: ["BPI-R3 Mini", "E-ink HAT", "Enclosure", "SD + PSU"],
      badge: "Popular",
    },
    {
      id: "fieldPack",
      name: "Field Pack",
      retailPrice: 219,
      priceDisplay: "$219",
      fulfillment: "direct",
      stripeKey: "fieldPack",
      source: "direct",
      description: "Core kit + M5Stack Cardputer + printed quick-start — desk + pocket.",
      includes: ["Cipherhorn core", "M5 Cardputer", "Quick-start guide"],
    },
    {
      id: "codStlPack",
      name: "COD STL + KSS print pack",
      retailPrice: 19,
      priceDisplay: "$19",
      fulfillment: "digital",
      stripeKey: "codStlPack",
      source: "direct",
      description: "Digital delivery — pocket clip, wall dock, Prusa/SuperSlicer profiles.",
      includes: ["COD clip STL", "Wall dock STL", "KSS profiles"],
      badge: "Digital",
    },
    {
      id: "digital",
      name: "Digital Pack",
      retailPrice: 15,
      priceDisplay: "$15",
      fulfillment: "digital",
      stripeKey: "digital",
      source: "direct",
      description: "Full repo assets, STL zip, sprites, marketing graphics — instant link.",
      includes: ["Repo bundle", "STL zip", "Sprites", "Release PNGs"],
    },
  ],
};
