/** Live config - I edit with my Stripe / PayPal / Cash App / Venmo details. */
window.HPL_PAYMENTS = {
  demoMode: true,
  stripeCustomerPortal: "",
  stripePaymentLinks: {
    digital: "",
    proMonthly: "",
    proYearly: "",
    mspMonitor: "",
    mspDefend: "",
    mspHarden: "",
    coreKit: "",
    fieldPack: "",
    boostFormulaCod: "",
    codStlPack: "",
    cydStandard: "",
    cydFieldCustom: "",
    crackbotBench: "",
    remotePossibility: "",
    bleBot: "",
    dsPwnagotchi: "",
    dsNetgotchi: "",
    dsNetgotchiPro: "",
    dsNightHunter: "",
    dsMeshtasticTBeam: "",
    dsMeshtasticHeltec: "",
    dsMeshtasticRAK: "",
    dsMeshtasticCase: "",
    dsHackberryZero: "",
    dsHackberryPi5: "",
    dsHackberryCM5: "",
    dsMarauderGps: "",
    dsMarauderBatteryMod: "",
    dsMarauderKoko: "",
    dsRaspberryPi5: "",
    dsOrangePi5: "",
    dsBananaPiR3: "",
    dsEsp32Cyd: "",
    dsWiringLab: "",
    dsKaliNetHunter: "",
    dsRtlSdrKit: "",
    dsNesdrSmart: "",
    dsLanTap: "",
    dsThrowingStarKit: "",
    dsEsp32WifiLab: "",
    dsUsbRubberDucky: "",
    dsHak5WifiPineapple: "",
  },
  paypal: { clientId: "", currency: "USD" },
  paypalSubscriptions: {
    proMonthly: { planId: "" },
    proYearly: { planId: "" },
    mspMonitor: { planId: "" },
    mspDefend: { planId: "" },
    mspHarden: { planId: "" },
  },
  paypalMe: { username: "" },
  cashapp: { cashtag: "" },
  venmo: { username: "" },
  supportEmail: "salvadorData@proton.me",
};
