---
- name: Install ClamAV
  ansible.builtin.apt:
    name:
      - clamav
      - clamav-daemon
    state: present

- name: Update virus definitions
  ansible.builtin.command: freshclam
  changed_when: true
  failed_when: false

- name: Enable freshclam
  ansible.builtin.service:
    name: clamav-freshclam
    state: started
    enabled: true
